# Generated by Django 2.2.8 on 2020-12-16 00:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20201215_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresoParticular',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ingreso_particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.IngresoParticular')),
            ],
        ),
    ]
