# Generated by Django 2.2.8 on 2020-12-16 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0025_auto_20201215_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 12, 15, 20, 11, 40, 118851)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2020, 12, 15, 20, 11, 40, 118851)),
        ),
    ]
