# Generated by Django 2.2.8 on 2021-02-04 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0026_auto_20201215_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 2, 4, 0, 42, 55, 691572)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2021, 2, 4, 0, 42, 55, 691572)),
        ),
    ]
