# Generated by Django 2.2.8 on 2021-03-15 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0027_auto_20210204_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_fin',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 3, 15, 16, 14, 33, 600002)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2021, 3, 15, 16, 14, 33, 600002)),
        ),
    ]
