# Generated by Django 2.2.8 on 2020-10-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0003_auto_20200930_0410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RpteParticular',
        ),
        migrations.DeleteModel(
            name='RpteSeguro',
        ),
    ]
